dataset_config:
  hateful_memes:
    data_dir: /home/roboticslab/Documents/MED-VQA/dataset/med-vqa-data/
    depth_first: false
    fast_read: false
    use_images: true
    use_features: false
    build_attributes:
      min_count: 1
      split_regex: " "
      keep:
        - ";"
        - ","
      remove:
        - "?"
        - "."
    images:
      train:
      - hateful_memes/
      val:
      - hateful_memes/
      test:
      - hateful_memes/
    features:
      train:
      - hateful_memes/defaults/features/detectron.lmdb
      val:
      - hateful_memes/defaults/features/detectron.lmdb
      test:
      - hateful_memes/defaults/features/detectron.lmdb
    annotations:
      train:
      - hateful_memes/train.jsonl
      val:
      - hateful_memes/dev_seen.jsonl
      test:
      - hateful_memes/test_seen.jsonl
    max_features: 100
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 14
          vocab:
            type: random
            vocab_file: /home/roboticslab/Documents/MED-VQA/dataset/med-vqa-data/vocabs/VQA_MED_2019_TRAIN_vocab.txt
          preprocessor:
            type: simple_sentence
            params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 50
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [224, 224]
            - ToTensor
            - GrayScaleTo3Channels
            - type: Normalize
              params:
                mean: [0.46777044, 0.44531429, 0.40661017]
                std: [0.12221994, 0.12145835, 0.14380469]
    return_features_info: false

  training: 
      max_updates: 22000


evaluation:
  predict_file_format: csv
