dataset_config:
  vqarad:
    data_dir: /home/roboticslab/Documents/MED-VQA/dataset/med-vqa-data/
    data_folder: vqa_rad
    build_attributes:
      min_count: 1
      split_regex: " "
      keep:
        - ";"
        - ","
      remove:
        - "?"
        - "."
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 10
          vocab:
            type: random
            vocab_file: vocabs/vqarad_question_vocab.txt
        preprocessor:
          type: simple_sentence
          params: {}
      answer_processor:
        type: multi_hot_answer_from_vocab
        params:
          num_answers: 1
          # Vocab file is relative to [data_dir]/[data_folder]
          vocab_file: vocabs/vqarad_answer_vocab.txt
          preprocessor:
            type: simple_word
            params: {}
